### ISSUE TITLE
단톡방이 지루해요

### ISSUE THREAD

**Issue by youngjinmo** [dahyezz/UniTime#18]
git/db 관련 대화가 대부분을 차지. 
일상적 대화를 공유하길 원하는건 아니나, 이대로 한달을 지내기엔 너무 지루할 것 같아요. 여러분 뒷통수만 보면서 코딩하려니까 쬐끔 심심하네요.
식사나 커피 혹은 맥주라도 한 잔 해서 아이스 브레이킹 합시다.

**Comment by dahyezz** [comment]
좋아요!@!@!@!@
